name: Rust CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Reqs
        run: sudo apt-get install libgtk-3-dev
      - name: Test
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
