name: Build and test
on:
  push:
jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
  build-and-test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
